### ISSUE TITLE
Content should not be gated behind completing the tutorial

### ISSUE THREAD

**Issue by hexagonrecursion** [naikari/naikari#13]
#### Naikari version
285536c1280de680a86d2f7a0884dcb6587cb0c1 (most recent main)

#### Describe the bug
In most games there is no downside to skipping the tutorial (e.g. if you have played the game before), but in naikari there is content that is directly or indirectly gated behind completing the tutorial:

- empire/emp_cargo00.lua
- empire/es_cargo.lua
- empire/es_longdistancecargo.lua
- empire/hakoi_pirates/emp_hp01.lua
- neutral/trader_escort.lua
- soromid/comingout/srm_comingout3.lua
- soromid/comingout/srm_comingout4.lua
- soromid/comingout/srm_comingout5.lua
- soromid/comingout/srm_comingout6.lua
- tutorial/reynir.lua
- baron/baron_baron.lua
- baron/baron_prince.lua
- tutorial/teenager.lua
- shadow/shadowrun.lua
- shadow/shadowvigil.lua
- shadow/darkshadow.lua

#### Expected behavior
It should be possible to access all the content without completing the tutorial.

#### Additional context (optional)
If you have ideas how to fix it, I can code them.

**Comment by onpon4** [comment]
I actually disagree on the grounds that Naikari's tutorial is designed to be a *hidden tutorial*: while internally we call them "tutorial", the way they're exposed to the player is intended to be as the first missions. In fact, some of the missions you list (teenager, reynir, and emp_cargo00) are considered to be a part of the tutorial (reynir shows how to use the Escape Jump, teenager shows how to disable and board ships, and emp_cargo00 serves as an introduction to the core game loop of checking for missions in the mission computer).

So while *gameplay-wise* the Empire Recruitment (emp_cargo00) mission is only shown after completing the Ian Structure missions is to make sure you've had some experience with basic navigation first, the *story* reason is that it's those jobs you do for Ian Structure which cause the Empire to notice you, and that it's during one of the missions you do for Ian Structure that pirates break through into Hakoi (which is the subject of the new Empire campaign we're developing for the next Naikari release).

The one thing I do agree with is that there shouldn't be a mission requirement that seems *arbitrary*. That's why the Teenager mission now stars Terra (the same mission-giver that gives you the outfitting tutorial), and while this hasn't been explained yet, an idea we have is that Terra operates the same business Reynir talked about, to tie those two together. Actually, come to think of it, that should probably be done in the outfitting tutorial mission.

Considering the follow tutorial specifically, I suppose one thing worth considering is that auto-following isn't strictly speaking *required* to do an escort mission, just highly recommended, so those particular dependencies might not be needed. The main reason we've put the follow tutorial as a prerequisite to them is to avoid giving an overly negative first impression of escort missions. Alternatively, if we keep the dependency, we'll have to provide some kind of story justification and put that into the story text before pushing the next Naikari release.

The connection between the Baron and Reynir missions should also be given more of a story justification, especially because the main reason we did that is so that the Baron mission can serve as a continuation of the escape jump tutorial (showing an example of a type of mission where you would want to use the maneuver).

How the Shadow missions connect to everything will need to be reconsidered. Shadowrun doesn't require any particular special skills, so perhaps it should be entirely disconnected, or perhaps connected to something else that can serve as a justification for why Rebina takes interest in the player (other than a hunch). We'll have to think on that a bit.

🕷️

**Comment by onpon4** [comment]
I've pushed a couple changes to address the deficiencies present:

1. I've removed the requirement to finish the follow tutorial for the escort missions. I suspect it's probably OK; the missions are perfectly doable without using auto-follow, and I can't think of any reasonable story reason for a dependency between them.
2. I've changed some story texts to better connect the stories of missions it requires and is required by.
3. I've removed most direct and indirect dependencies on completion of the Space Family mission, based on the justification that the tutorial aspect (teaching the basics of how to board something) actually happens in the event which is prior to the space family mission and that event is guaranteed to spawn at least once when you get to hostile territory.

I understand this isn't exactly the solution you are advocating for of course but the design philosophy we're going with is that there isn't a segmented-off "tutorial" section, rather the Ian Structure and Terra missions are a part of the story. The Empire campaign we're working on is directly connected to events that take place as you work for Ian Structure, and we'll also be extending the idea of Ian Structure becoming a pilot at some point, coming off of the follow tutorial and developing a story arc for his character. So I'll close this as completed (for the deficiencies I addressed), but feel free to either reopen or open a new issue if there's other specific deficiencies you notice in how this is handled.

🕷️
