### ISSUE TITLE
AI in some missions can not jump if the player is slow

### ISSUE THREAD

**Issue by hexagonrecursion** [naikari/naikari#18]
#### Naikari version
v0.10.0 (from flathub)

#### Describe the bug
Ian from Ian's Courage can not jump if the player's maximum speed is too low.

#### To Reproduce
1. Switch your ship to Soromid Vox (I did not test with other ships)
2. Start the Ian's Courage mission
3. Follow Ian to the jump
4. When Ian reaches the jump, he just spins there instead of jumping; the mission soft-locks

#### Expected behavior
Ian jumps to the next system

#### Screenshots (optional)
[Screencast from 2023-09-12 16-46-32.webm](https://github.com/naikari/naikari/assets/52621858/b759c17c-57b0-4404-b499-a9f59592c110)

#### Additional context (optional)
1. From my lua debugging this appears to be caused by ai.minbrakedist() returning a negative number which prevents the __hyp_approach task from completing
2. Unsetting the speed limit on Ian's ship fixes this issue
3. From gdb: In the below code vel is 0.0001 because cur_pilot->speed is 0.0001 (may be related to pilot_updateMass), but time is calculated based on VMOD(cur_pilot->solid->vel) which is, for example, 5.345411405711415. This causes dist to be negative
https://github.com/naikari/naikari/blob/1cab4ac7426e5055e885e4f4e8868597e380cd21/src/ai.c#L1492-L1504
4. I think replacing the line 1498 with `vel = VMOD(cur_pilot->solid->vel)` might fix this (did not check).

**Comment by onpon4** [comment]
I'm looking at this and I don't think the change you suggest would actually be correct, since that "speed" variable is used elsewhere as well in the exact same way. I also note that this particular code has looked like this for many years; that doesn't necessarily mean it's doing the right thing, but it does mean that it's likely that it was working without noticeable faults until recently.

The only code related to this that I think has ever changed in Naikari's development history is the AI code itself, so it's possible there's some sort of issue with the numbers that has only come to light as a result of those. We'll have to try to figure out what that might be. If it's easy to reproduce, perhaps a git bisect could be in order just to narrow down exactly what change led to this. I'll look into things more closely in a few days, in any case. Perhaps a whole rewrite might even be in order. (Naev actually did a full rewrite, which we tried out with 5112da3e715d6726cd975563aaab6e4c174a8a14, but we subsequently reverted that because it seemed to not work correctly.)

**Comment by onpon4** [comment]
I think my mind on what I think seems correct has changed and I think your initial conclusion seems right, after looking at it for a few more minutes. I'll want to do some checks to verify, thô, and look into why that "speed" variable is getting set <= 0 (which is almost certainly why it got set to 0.0001), since that could be indicative of a deeper problem in the code.

**Comment by onpon4** [comment]
Ok, so, it looks like our initial reservations were right. That "speed" usage was there for a good reason: because it's the drift speed. Looks like what was happening was speed could become zero if the speed limit was low enough, and that would mean that brake distance actually should be zero (as braking isn't actually needed in that case). So I've changed it so that completely not drifting is less likely, added a MAX call to make sure minbrakedist doesn't return a negative number (returns zero instead), and I'll need to also add a guard in the AI code itself to handle the case of min brake distance being extremely small, probably just by also recognizing being inside the jump radius as a condition to start braking.

🕷️

**Comment by onpon4** [comment]
Just finished adding in that last protection and the totality of the changes seems to make things pretty sturdy now. I didn't specifically test the mission you mentioned, but I did test some generic AI pilots with an extremely small speed limit applied and the fix to them should also work for the mission pilot. Please let us know if the bug persists in the latest git revision. Assuming there isn't a problem with the fix, we'll be pushing out a 0.10.1 bugfix release soon.
