### ISSUE TITLE
Question on CPU use

### ISSUE THREAD

**Issue by cig0** [naikari/naikari#26]
#### Describe the issue
Hi :wave: 

_Context:_ Yesterday, I learned about Naikari while browsing similar games at the Flathub store. Being a long-time Naev fan, I had to give Naikari a try. Things got interesting when the good old "Naev music theme" kicked in when I launched the game. So I got to the FAQ section, followed the rabbit down the hole, and learned about the discussion thread referenced there. I'm telling this because the comparison I'm about to make next is in good faith, with zero intentions of spawning a meaningless conversation. Life's too short to waste on stuff not close to our hearts.

_The issue:_ I can see in `top` that Naikari consumes as much as double CPU cycles than Naev, sometimes thrice (even when at the menus or with the game running in the background):

System specs *desktop*:
```asciidoc
OS: Fedora Linux 39 (Kinoite) x86_64
Kernel: 6.7.9-200.fc39.x86_64
DE: KDE Plasma 5.27.11
WM: KWin (Wayland)
CPU: Intel(R) Core(TM) i9-9900K (16) @ 5.00 GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
```
![Screenshot_20240328_173404](https://github.com/naikari/naikari/assets/394089/25b50da2-a05d-46e3-91d1-b6ea860f94c1)

System specs _laptop_:
```asciidoc
OS: Fedora Linux 39 (Kinoite) x86_64
Kernel: 6.7.9-200.fc39.x86_64
DE: KDE Plasma 5.27.11
WM: KWin (Wayland)
CPU: 11th Gen Intel(R) Core(TM) i7-11370H (8) @ 4.80 GHz
GPU: Intel Iris Xe Graphics
```
![Spectacle-Screenshot_20240328_180028](https://github.com/naikari/naikari/assets/394089/b2d03716-1343-4ce5-9a89-7d018041b2e8)

Are these values expected?

#### Additional context (optional)
Running Naikari version **0.12.0**.
Both Naikari and Naev are installed as flatpaks.

Thanks,
-Martín

**Comment by onpon4** [comment]
Naikari's codebase is based on a past revision of Naev (I want to say roughly version 0.8.0), so I don't consider such a difference alarming. I know that Naev has added some optimizations that I haven't added, such as the use of quadtrees for collision detection, so changes such as those could explain the discrepancy, as well as changes introduced here. In addition to engine differences (of which there are many), things like how many ships spawn and how the AI code is written can have an effect. What matters the most to me as far as performance goes is whether the game runs well, so that's what I tailor performance-related tinkering to.

In any case, performance characteristics might change quite a bit with version 0.13.0, given the [vast sweeping changes](https://github.com/naikari/naikari/discussions/25) I'm making for that release.

**Comment by cig0** [comment]
> What matters the most to me as far as performance goes is whether the game runs well

If that's the case, rest assured that Naikari runs buttery-smooth!

> In any case, performance characteristics might change quite a bit with version 0.13.0, given the [vast sweeping changes](https://github.com/naikari/naikari/discussions/25) I'm making for that release.

:rocket:
